name: link-checker

services:

  crawler:
    build:
      context: ./.docker/siteone-crawler
      dockerfile: Dockerfile
    volumes:
      - ./tmp:/siteone-crawler/tmp
      - ./output:/siteone-crawler/output

  analyser:
    build:
      context: ./docker/analyser
      dockerfile: Dockerfile
    volumes:
      - ./tmp:/tmp/crawl-data
