<?php declare(strict_types=1);

namespace alanrogers\linkchecker\app\Commands;

use alanrogers\linkchecker\app\Exceptions\InvalidFile;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

#[AsCommand(
    name: 'crawl:process',
    description: 'Processes a report generated by the `crawl:site` command.'
)]
class ProcessCrawl extends Command
{
    /**
     * @throws InvalidFile
     */
    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $file = $input->getArgument('file');
        if (!$file) {
            throw new InvalidFile('Invalid file');
        }
    }

    protected function configure(): void
    {
        $this->addArgument(
            'file',
            InputArgument::REQUIRED,
            'The file to process.'
        );
    }
}